repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        files: ^api
        args: [--config-file, mypy.ini]
        additional_dependencies:
          [
            fastapi,
            starlette,
            multidict,
            pydantic,
            aiohttp,
            SQLAlchemy==1.4.11,
            "https://github.com/sqlalchemy/sqlalchemy2-stubs/archive/refs/heads/master.zip",
          ]
  - repo: https://github.com/pycqa/flake8
    rev: "3.9.1"
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: "5.8.0"
    hooks:
      - id: isort
