services:
  - type: web
    name: jokull-sunna
    env: python
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        value: sqlite:////var/data/database.db
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 5
    buildCommand: NODE_ENV=production poetry install --no-dev && pip install gunicorn && yarn install --production=false && yarn run export
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker api:app
